#!/usr/bin/env python3
"""Deterministic synthetic convex-MIQP instances for the MIQP-01 benchmark stratum.

Contract: docs/contracts/miqp-node-bounds.md §7.8 (separate convex MIQP stratum,
statuses as measured, no speed claim, never merged into the linear MIP summary).

The repository checks in no convex MIQP dataset, so this generator emits five
small free-MPS models under data/miqp/ with one provenance JSON per file:

- Q is positive semidefinite by construction (B'B + D, or its negation for the
  maximize instance, which is therefore concave).
- QUADOBJ lists the upper triangle of Q; this repository reads the free-MPS
  standard objective c'x + 0.5 * x'Qx (parser symmetrises off-diagonal entries).
- Every row bound is derived from an explicit feasible 0/1 witness, so each
  instance is feasible by construction.

Usage: python3 scripts/generators/gen_miqp01_instances.py [--out-dir data/miqp]
"""

import argparse
import hashlib
import json
import random
from datetime import date
from pathlib import Path

SEED = 20261001
CONVENTION = ("free MPS QUADOBJ upper triangle; objective c'x + 0.5 x'Qx; "
              "listed diagonal entry (i,i,v) contributes 0.5*v*x_i^2")
CHANGE = "initial synthetic convex MIQP benchmark instance for MIQP-01 contract section 7.8"


def psd_from(seed: int, rows: int, n: int, diag: float) -> list[list[float]]:
    rng = random.Random(seed)
    b = [[rng.randint(-2, 2) for _ in range(n)] for _ in range(rows)]
    q = [[diag if i == j else 0.0 for j in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            q[i][j] += sum(b[r][i] * b[r][j] for r in range(rows))
    return q


def diagonal(n: int, start: float, step: float) -> list[list[float]]:
    return [[(start + step * i) if i == j else 0.0 for j in range(n)] for i in range(n)]


def emit_mps(name: str, sense: str, lin: list[float], q: list[list[float]],
             row_names: list[str], row_kinds: list[str], rows_a: list[list[float]],
             rhs: list[float], witness: list[int]) -> str:
    n = len(lin)
    lines = [f"* synthetic convex MIQP instance generated by {Path(__file__).name}",
             f"* objective convention: {CONVENTION}",
             f"* feasible witness: {' '.join(str(w) for w in witness)}",
             f"NAME          {name}", "OBJSENSE", f" {sense}", "ROWS",
             " N  OBJ"]
    for rk, rn in zip(row_kinds, row_names):
        lines.append(f" {rk}  {rn}")
    lines.append("COLUMNS")
    for j in range(n):
        lines.append(f"    X{j + 1:<6}  OBJ  {lin[j]:g}")
        for i, rn in enumerate(row_names):
            if rows_a[i][j] != 0.0:
                lines.append(f"    X{j + 1:<6}  {rn}  {rows_a[i][j]:g}")
    lines.append("QUADOBJ")
    for i in range(n):
        for j in range(i, n):
            if q[i][j] != 0.0:
                lines.append(f"    X{i + 1:<6}  X{j + 1:<6}  {q[i][j]:.17g}")
    lines.append("RHS")
    for i, rn in enumerate(row_names):
        lines.append(f"    RHS1  {rn}  {rhs[i]:g}")
    lines.append("BOUNDS")
    for j in range(n):
        lines.append(f"    BV BOUND1  X{j + 1}")
    lines.append("ENDATA")
    return "\n".join(lines) + "\n"


def build_rows(n: int, spec, rng: random.Random):
    """Return (row_names, kinds, matrix, rhs, witness); bounds derive from the witness."""
    witness = [1 if rng.random() < 0.35 else 0 for _ in range(n)]
    row_names, kinds, matrix, rhs = [], [], [], []
    for i, (kind, coeffs, bound_kind, slack) in enumerate(spec):
        a = [0.0] * n
        for j, v in coeffs.items():
            a[j] = v
        value = sum(a[j] * witness[j] for j in range(n))
        if bound_kind == "le":
            r = value + slack
        elif bound_kind == "ge":
            r = max(0.0, value - slack)
        else:
            r = value
        row_names.append(f"C{i + 1}")
        kinds.append(kind)
        matrix.append(a)
        rhs.append(r)
    return row_names, kinds, matrix, rhs, witness


def generate(out_dir: Path, seed: int) -> list[dict]:
    out_dir.mkdir(parents=True, exist_ok=True)
    records = []
    plans = [
        ("miqp_binquad_n12", "minimize", 12, "diag",
         [("L", {j: 1.0 for j in range(12)}, "le", 1.0),
          ("G", {j: 1.0 for j in range(12)}, "ge", 1.0)]),
        ("miqp_coupling_n20", "minimize", 20, "coupling",
         [("L", {j: 1.0 for j in range(0, 8)}, "le", 1.0),
          ("L", {j: 1.0 for j in range(8, 16)}, "le", 1.0),
          ("G", {j: 1.0 for j in range(20)}, "ge", 2.0),
          ("L", {j: float(j + 1) for j in range(20)}, "le", 40.0)]),
        ("miqp_dense_block_n16", "minimize", 16, "dense",
         [("L", {j: 1.0 for j in range(16)}, "le", 0.0),
          ("G", {j: 1.0 for j in range(16)}, "ge", 0.0)]),
        ("miqp_maximize_n18", "maximize", 18, "max",
         [("L", {j: 1.0 for j in range(18)}, "le", 2.0),
          ("G", {j: 1.0 for j in range(0, 18, 2)}, "ge", 1.0),
          ("L", {j: float(j + 1) for j in range(18)}, "le", 60.0)]),
        ("miqp_large_n40", "minimize", 40, "large",
         [("L", {j: 1.0 for j in range(0, 14)}, "le", 2.0),
          ("L", {j: 1.0 for j in range(14, 28)}, "le", 2.0),
          ("G", {j: 1.0 for j in range(40)}, "ge", 3.0),
          ("L", {j: float(j + 1) for j in range(40)}, "le", 260.0),
          ("G", {j: 2.0 if j % 3 else 1.0 for j in range(40)}, "ge", 25.0)]),
    ]
    for k, (name, sense, n, flavor, spec) in enumerate(plans):
        rng = random.Random(seed + k)
        if flavor == "diag":
            q = diagonal(n, 2.0, 0.7)
            lin = [round(5.0 - 0.3 * j, 6) for j in range(n)]
        elif flavor == "coupling":
            q = psd_from(seed + k, 5, n, 3.0)
            lin = [round(rng.uniform(1.0, 9.0), 6) for j in range(n)]
        elif flavor == "dense":
            q = psd_from(seed + k, 4, n, 1.0)
            lin = [round(rng.uniform(0.0, 1.0), 6) for j in range(n)]
        elif flavor == "max":
            q = [[-v for v in row_] for row_ in psd_from(seed + k, 4, n, 2.0)]
            lin = [float(3 + j % 5) for j in range(n)]
        else:
            q = psd_from(seed + k, 6, n, 1.0)
            lin = [round(4.0 - 0.08 * j, 6) for j in range(n)]
        kinds_spec = [(kind, coeffs, bk, slack) for (kind, coeffs, bk, slack) in spec]
        row_names, kinds, matrix, rhs, witness = build_rows(n, kinds_spec, rng)
        text = emit_mps(name, sense.upper(), lin, q, row_names, kinds, matrix, rhs, witness)
        path = out_dir / f"{name}.mps"
        path.write_text(text, encoding="utf-8")
        quad_nnz = sum(1 for i in range(n) for j in range(i, n) if q[i][j] != 0.0)
        proof = {
            "fixture": path.name,
            "generator": "scripts/generators/gen_miqp01_instances.py",
            "generator_args": {"seed": seed + k, "family": flavor, "n": n},
            "regeneration_date": date.today().isoformat(),
            "change": CHANGE,
            "model_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "problem_class": "MIQP",
            "convexity": ("Q positive definite (B'B + positive diagonal) by construction"
                          if sense == "minimize"
                          else "Q negative semidefinite (negated B'B + diagonal), concave maximize"),
            "direction": sense,
            "rows": len(row_names),
            "columns": n,
            "quadratic_nonzeros": quad_nnz,
            "linear_constraint_nonzeros": sum(len([v for v in a if v]) for a in matrix),
            "objective_convention": CONVENTION,
            "feasible_witness": witness,
            "source": "synthetic; generated in-repo, not an external dataset",
        }
        (out_dir / f"{name}.provenance.json").write_text(
            json.dumps(proof, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        records.append(proof)
        print(f"[+] {path}  n={n} rows={len(row_names)} quad_nnz={quad_nnz} {sense}")
    return records


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="data/miqp")
    parser.add_argument("--seed", type=int, default=SEED)
    args = parser.parse_args()
    generate(Path(args.out_dir), args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
